apiVersion: apps/v1
kind: Deployment
metadata:
  name: petcam
  labels:
    app: petcam
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petcam
  template:
    metadata:
      labels:
        app: petcam
    spec:
      containers:
      - name: petcam
        image: kumari3123/petcam:4
        ports:
        - containerPort: 8443
